hydra:
  job:
    name: ${backbone.name}_emb
  run:
    dir: /home/tigina/bug-localization/output/${hydra:job.name}
  job_logging:
    root:
      handlers: [console, file]
backbone:
  _target_: src.baselines.backbones.emb.hf_emb_backbone.HfEmbBackbone
  name: codet5
  pretrained_path: None
  parameters:
  model_name: Salesforce/codet5p-110m-embedding
  ranker:
    _target_: src.baselines.backbones.emb.rankers.cosine_distance_ranker.CosineDistanceRanker
data_source:
  _target_: src.baselines.data_sources.hf_data_source.HFDataSource
  repos_dir:  /mnt/data/shared-data/lca/repos_updated
  cache_dir: null
  hub_name: tiginamaria/bug-localization
  configs:
    - py
    - java
    - kt
  split: test
output_path: /Users/Maria.Tigina/PycharmProjects/lca-baselines/data/lca-bug-localization