backbone:
  _target_: src.baselines.backbones.gen.openai_gen_backbone.OpenAIGenBackbone
  prompt:
    _target_: src.baselines.prompts.file_list_prompt.FileListPrompt
  model_name: gpt-3.5-turbo-16k
  api_key: null
  parameters:
    seed: 76097149
    temperature: 0
data_src:
  _target_: src.baselines.data_sources.hf.HFDataSource
  cache_dir: null
  hub_name: tiginamaria/bug-localization
  configs:
    - py
    - java
    - kt
  split: test
output_path: /Users/Maria.Tigina/PycharmProjects/lca-baselines/data/lca-bug-localization
