backbone:
  _target_: src.baselines.backbones.OpenAIBackbone
  prompt:
    _target_: src.baselines.prompts.FileListPrompt
  model_name: gpt-4-1106-preview
  api_key: null
  parameters:
    seed: 76097149
    temperature: 0.8
data:
  _target_: src.baselines.data_sources.HFDataSource
  cache_dir: null
  hub_name: tiginamaria/bug-localization
  configs:
  - py
  - java
  - kt
  split: test
