hydra:
  job:
    name: ${backbone.name}_${backbone.model_name}
  run:
    dir: /home/tigina/bug-localization/output/${hydra:job.name}
  job_logging:
    root:
      handlers: [console, file]
backbone:
  _target_: src.baselines.backbones.agent.openai_agent_backbone.OpenAIAgentBackbone
  name: openai_agent
  model_name: gpt-4-1106-preview
  api_key: null
  prompt:
    _target_: src.baselines.backbones.agent.prompts.agent_simple_prompt.AgentSimplePrompt
data_source:
  _target_: src.baselines.data_sources.hf_data_source.HFDataSource
  repos_dir:  /mnt/data/shared-data/lca/repos_updated
  cache_dir: null
  hub_name: tiginamaria/bug-localization
  configs:
    - py
    - java
    - kt
  split: test