backbone:
  _target_: src.baselines.backbones.emb.tfidf_emb_backbone.TfIdfEmbBackbone
  pretrained_path: null
  tokenizer:
    _target_: src.baselines.backbones.emb.tokenizers.nltk_tokenizer.NltkTokenizer
  ranker:
    _target_: src.baselines.backbones.emb.rankers.cosine_distance_ranker.CosineDistanceRanker
data_src:
  _target_: src.baselines.data_sources.hf.HFDataSource
  cache_dir: null
  hub_name: tiginamaria/bug-localization
  configs:
    - py
    - java
    - kt
  split: test
output_path: /Users/Maria.Tigina/PycharmProjects/lca-baselines/data/lca-bug-localization
