baseline_type:
  embed
model:
  name: tfidf
  tokenizer:

#    name: bpe
#    vocab_size: 10000
#    min_frequency: 2
#    pretrained_path: /bpe

    name: codet5
    checkpoint: Salesforce/codet5-large
    min_frequency: 2

#    name: nltk
